services:
  user-api:
    build:
      context: service/user
      dockerfile: Dockerfile
    ports:
      - "18081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
      - kafka

  balance-api:
    build:
      context: service/balance
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
      - USER_SERVICE_URL=http://user-api:8081
    depends_on:
      - mysql
      - redis
      - kafka

  coupon-api:
    build:
      context: service/coupon
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
      - USER_SERVICE_URL=http://user-api:8081
    depends_on:
      - mysql
      - redis
      - kafka

  product-api:
    build:
      context: service/product
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
      - kafka

  order-api:
    build:
      context: service/order
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
      - USER_SERVICE_URL=http://user-api:8081
      - PRODUCT_SERVICE_URL=http://product-api:8084
      - COUPON_SERVICE_URL=http://coupon-api:8083
    depends_on:
      - mysql
      - redis
      - kafka

  payment-api:
    build:
      context: service/payment
      dockerfile: Dockerfile
    ports:
      - "18086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
      - ORDER_SERVICE_URL=http://order-api:8085
      - BALANCE_SERVICE_URL=http://balance-api:8082
      - COUPON_SERVICE_URL=http://coupon-api:8083
    depends_on:
      - mysql
      - redis
      - kafka

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: application
      MYSQL_PASSWORD: application
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
    command: redis-server --appendonly yes

  kafka:
    image: apache/kafka:4.1.0
    ports:
      - "9094:9094"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - user-api
      - balance-api
      - coupon-api
      - product-api
      - order-api
      - payment-api

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - influxdb

volumes:
  kafka-data:
  mysql-data:
  influxdb-data:

networks:
  default:
    driver: bridge
