server:
  port: 8082

spring:
  application:
    name: ecommerce-balance-service
  config:
    import:
      - client.yml
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce
  jpa:
    show-sql: false
